### ISSUE TITLE
Ola pode me ajudar 

### ISSUE THREAD

**Issue by sonickbh** [Colgate13/Blaze-Bot-telegram#2]
Como faço para ele retornar loss e branco

**Comment by Colgate13** [comment]
Opa, tente debugar o arquivo "/src/modules/Tiles/useCases/BlazeTiles/Service/CheckTile.ts"

Caso este arquivo esteja retornando certo verifique o arquivo "/src/modules/Bot/Bot.ts"

**Comment by Colgate13** [comment]
Qualquer melhoria pode realizar um Fork e um pull request que eu aceito e faço o merge

**Comment by sonickbh** [comment]
Tentei por umas 2h e não consegui resolver


Em qui., 4 de ago. de 2022 07:59, Gabriel Barros Feitosa Sá <
***@***.***> escreveu:

**Comment by Colgate13** [comment]
Tenta adicionar console.log no retorno do arquivo "/src/modules/Tiles/useCases/BlazeTiles/Service/CheckTile.ts" para saber se esta retornando de acordo. Eu quero fazer melhorias no bot também mas por enquanto estou bastante ocupado.

**Comment by sonickbh** [comment]
Coloquei não mudou nada vou estudar com esforço vou conseguir fazer ele
marcar loss e reconhecer o branco quero por histórico de Green e Los

Em sex., 5 de ago. de 2022 07:39, Gabriel Barros Feitosa Sá <
***@***.***> escreveu:

**Comment by Colgate13** [comment]
Eu entendo, você conseguiu descobrir se esta retornando de acordo?? se tiver o problema esta em outro lugar, qualquer duvida sobre algum trecho coloca aqui que eu ajudo, to meio ocupado para mexer diretamente mesmo mais vou mexer logo logo também

**Comment by sonickbh** [comment]
Não consegui

Em sex., 5 de ago. de 2022 13:54, Gabriel Barros Feitosa Sá <
***@***.***> escreveu:

**Comment by sonickbh** [comment]
Eu sou meio fraco mais tô aprendendo me instigou a estudar

Em sáb., 6 de ago. de 2022 10:43, sonick wellington ***@***.***>
escreveu:

**Comment by sonickbh** [comment]
Como coloco ele para ir só até G1 ?

Em sáb., 6 de ago. de 2022 10:46, sonick wellington ***@***.***>
escreveu:

**Comment by Colgate13** [comment]
Gale 1?

No arquivo /src/modules/Tiles/useCases/BlazeTiles/Service/CheckTile.ts linha 32 tem um for, deixa ele assim =>let i = 0; i < 1; i++)

Depois so troca a mensagem que ele esta enviando e pronto,

Você esta rodando na sua maquinha? Tente colocar console.log() igual eu falei acima, e validar se aquelas arquivos estão retornando certo, coloca os console.log antes do return, e dentro dos () coloca a variavel o objeto que o return vai retornar, caso esteja retornando corretamente no arquivo /src/modules/Tiles/useCases/BlazeTiles/Service/CheckTile.ts então ja tenho uma ideia de onde pode esta o erro.

**Comment by sonickbh** [comment]
Tá vou fazer isto a noite uma coisa que conseguir foi ajustar o relógio
lembra que os minutos de 00:09 ficava sem o 0 tipo 9:03 ficava 9:3 ajustei

Em dom., 7 de ago. de 2022 20:39, Gabriel Barros Feitosa Sá <
***@***.***> escreveu:

**Comment by Colgate13** [comment]
Boa!!! Faz o fork e dps cria o pull request para o repo original que eu faço o merge

**Comment by sonickbh** [comment]
Você tem ideia mais ou menos aonde pode está o erro para ele não marcar o
branco nem loss ?

Em ter., 9 de ago. de 2022 22:16, Gabriel Barros Feitosa Sá <
***@***.***> escreveu:

**Comment by Colgate13** [comment]
No arquivo CheckTiles.ts eu acho

**Comment by Colgate13** [comment]
@sonickbh Como esta indo?

**Comment by sonickbh** [comment]
Sem sucesso

Em seg., 22 de ago. de 2022 17:57, Gabriel Barros Feitosa Sá <
***@***.***> escreveu:

**Comment by sonickbh** [comment]
Está em uma vps de teste windows server

Esta retornando corretamente

Em ter., 9 de ago. de 2022 08:46, sonick wellington ***@***.***>
escreveu:

**Comment by Colgate13** [comment]
Ola, como você configurou para retornar corretamente? Qualquer cosa fazar um pull request e eu mergeo
